# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yo0fJV-4jrJgaeqIUekpFzF4HdqLqPqx
"""

from resnet.ResNet import resnet18, resnet152